version: '3.5'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/jarvis:/usr/src/app/jarvis
    ports:
      - 5000:5000
    env_file: ./server/.env
    depends_on:
      - postgres

  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/app'
    ports:
      - 8080:8080
    depends_on:
      - server